### ISSUE TITLE
D9VK Lutris Error (not a gzip file)

### ISSUE THREAD

**Issue by robzombie91** [Tk-Glitch/PKGBUILDS#370]
019-11-06 17:24:32,168: Running Lutris 0.5.3
2019-11-06 17:24:32,168: Using NVIDIA drivers 435.27.03 for x86_64
2019-11-06 17:24:32,168: GPU: GeForce GTX 1070
2019-11-06 17:24:32,168: GPU: 10DE:1B81 3842:6173 using nvidia drivers
2019-11-06 17:24:32,249: Vulkan is supported
2019-11-06 17:24:32,250: Updating DXVK versions
2019-11-06 17:24:32,638: Updating D9VK versions
2019-11-06 17:24:40,786: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-11-06 17:24:40,786: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-11-06 17:24:40,793: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-11-06 17:24:40,835: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-11-06 17:24:40,835: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-11-06 17:24:40,835: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-11-06 17:24:40,835: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-11-06 17:24:41,137: Extraction failed: not a gzip file
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.7/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'No')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 116, in extract_archive
    _do_extract(path, temp_path, opener, mode, extractor)
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 164, in _do_extract
    handler = opener(archive, mode)
  File "/usr/lib/python3.7/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
2019-11-06 17:24:41,137: Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f0d1c45ed50>>: not a gzip file
<class 'lutris.util.extract.ExtractFailure'> not a gzip file
  File "/usr/lib/python3.7/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 772, in prelaunch
    self.prefix_path, arch=self.wine_arch, version=self.runner_config.get("d9vk_version")
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 751, in setup_dxvk
    dxvk_manager=dxvk_manager,
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 733, in toggle_dxvk
    dxvk_manager.download()
  File "/usr/lib/python3.7/site-packages/lutris/util/wine/dxvk.py", line 131, in download
    extract_archive(dxvk_archive_path, self.dxvk_path, merge_single=True)
  File "/usr/lib/python3.7/site-packages/lutris/util/extract.py", line 119, in extract_archive
    raise ExtractFailure(str(ex))
2019-11-06 17:24:41,138: not a gzip file

**Comment by Tk-Glitch** [comment]
What am I looking at? What are you trying to do?

**Comment by robzombie91** [comment]
@Tk-Glitch The output log of trying to run a game with TkG d9vk with lutris. It says not a gzip file when trying to launch anything with the above after building d9vk with your script

**Comment by Tk-Glitch** [comment]
I can't reproduce the issue. Please explain what you did in detail.

**Comment by robzombie91** [comment]
Ran a git pull to pull recent additions. went into the dxvk tools folder. ran sudo ./upd9vk build, then ran sudo ./upd9vk lutris

**Comment by robzombie91** [comment]
[lutris output 1](https://i.imgur.com/w8TP3mz.png)

**Comment by robzombie91** [comment]
Wierd, Must have been my pc because now its mysteriously working
Schrodinger's Computer

**Comment by Tk-Glitch** [comment]
Make sure your runner options look like this:
![Screenshot_20191107_140109](https://user-images.githubusercontent.com/741977/68391096-1b547300-0167-11ea-83d1-c6c55af43bbf.png)

Make sure `~/.local/share/lutris/runtime/d9vk/TkG` exists and is populated.
If that still doesn't work, that's a Lutris issue.

**Comment by Tk-Glitch** [comment]
Oh. Okay then :frog:

**Comment by robzombie91** [comment]
It works now, wasnt working yesterday

**Comment by openglfreak** [comment]
@robzombie91 You said you used sudo to build and update d9vk. Don't use sudo for that.

**Comment by Tk-Glitch** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^
